name: Deploy Lambda Function
on:
  push:
    branches: [ main]
  pull_request:
    branches: [ master ]
  workflow_dispatch:

jobs:
  release:
    name: Deploy lambda function
    runs-on: [ ubuntu-latest]
    steps:
      - uses: actions/checkout@v2

      - name: Get changed files
        id: changed-files
        uses: tj-actions/changed-files@v34

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: eu-west-2
          role-duration-seconds: 1200
          role-session-name: MySessionName

      - name: List all changed files
        run: |
          for file in ${{ steps.changed-files.outputs.all_changed_files }}; do
            echo "$file was changed";

          #   file_name="$(cut -d '.' -f 1 <<<"$file")";

          #   zip -r9 $file_name.zip $file_name.py;

          #   function does_lambda_exist() {
          #   echo "$1 lambda is getting created or updated";
          #   aws lambda get-function --function-name $1 > /dev/null 2>&1
          #   if [ 0 -eq $? ]; then
          #     echo "Lambda '$1' exists" &&
          #     aws lambda update-function-code --function-name $1 --zip-file fileb://$1.zip
          #   else
          #     echo "Lambda '$1' does not exist" &&
          #     aws lambda create-function \
          #   --function-name $1 \
          #   --runtime python3.9 \
          #   --zip-file fileb://$1.zip \
          #   --handler $1.handler \
          #   --role arn:aws:iam::184261415726:role/service-role/testingPackage-role-0xjvn09o
          #   fi
          # }

          # does_lambda_exist  $file_name
          # done
#       - name: zip Lambda Function
#         run: |
#                   zip -r9 lambda.zip lambdaFunction.py
#       - name: AWS Deploy
#         run: |
#               aws lambda update-function-code --function-name NameOfLambdaFunction --zip-file fileb://lambda.zip
