name: Deploy Lambda Function
on:
  push:
    branches: [ main]
  pull_request:
    branches: [ master ]
  workflow_dispatch:

jobs:
  release:
    name: Deploy lambda function
    runs-on: [ ubuntu-latest]
    steps:
      - uses: actions/checkout@v2

      - name: Get changed files
        id: changed-files
        uses: tj-actions/changed-files@v34

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: eu-west-2
          role-duration-seconds: 1200
          role-session-name: MySessionName

      - name: List all changed files
        run: |
          for file in ${{ steps.changed-files.outputs.all_changed_files }}; do
            echo "$file was changed";
            my_arr=($file | tr ".")
            file_name=${my_arr[0]}
            echo "$file_name lambda is getting created"
            zip -r9 file_name.zip file_name.py;
            aws lambda update-function-code --function-name file_name --zip-file fileb://file_name.zip
          done
#       - name: zip Lambda Function
#         run: |
#                   zip -r9 lambda.zip lambdaFunction.py
#       - name: AWS Deploy
#         run: |
#               aws lambda update-function-code --function-name NameOfLambdaFunction --zip-file fileb://lambda.zip
